branch-defaults:
  master:
    environment: adv-text-flask-env
environment-defaults:
  adv-text-flask-env:
    branch: null
    repository: null
global:
  application_name: adv_text_playground
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:us-east-1::platform/Python 3.6 running
    on 64bit Amazon Linux/2.8.2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
